number = input('Enter amount of purchase')
number = int(number)
statetax = (number * .05)
countytax = (number * .025)
print('Purchase:')
print(number)
print('State tax:')
print(statetax)
print('County tax:')
print(countytax)
print('Total sales tax:')
print(statetax + countytax)
print('Total:')
print(number + statetax + countytax)