number1 = input('Enter price of 1st item')
number1 = int(number1)
number2 = input('Enter price of 2nd item')
number2 = int(number2)
number3 = input('Enter price of 3rd item')
number3 = int(number3)
number4 = input('Enter price of 4th item')
number4 = int(number4)
number5 = input('Enter price of 5th item')
number5 = int(number5)
subtotal = (number1 + number2 + number3 + number4 + number5)
salestax = (number1 * .07 + number2 * .07 + number3 * .07 + number4 * .07 + number5 * .07)
print('subtotal:')
print(number1 + number2 + number3 + number4 + number5)
print('sales tax:')
print(number1 * .07 + number2 * .07 + number3 * .07 + number4 * .07 + number5 * .07)
print('total:')
print(subtotal + salestax)